config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :clients
  resources :products
  resources :pictures
  resources :comments, only: %i[index new show create]

  namespace :admin do
    resources :comments, only: %i[destroy]
  end

  # scope module: 'admin' do
  #   resources :comments, only: %i[destroy]
  # end

  # scope '/admin' do
  #   resources :comments
  # end

  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  EMAIL_REGEXP = /\w+@[a-z]+\.[a-z]+/
  PHONE_REGEXP = /(\+375|80)\s(29|33|44)\s\d{3}-?\s?\d{2}-?\s?\d{2}/
  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :comments

  # after_find { |client| puts "You have found an object!" }
  # after_initialize { |client| puts "You have initialized an object!" }
  after_destroy :destroy_action
  after_save :success
  after_create :success
  after_create_commit :client_saved_to_db

  validates :first_name, :last_name,
            :email, :phone, presence: true

  validates :first_name, :last_name,
            length: { minimum: 3, message: 'Input correct please name category' }

  validates :email,
            uniqueness: { case_sensitive: false },
            format: { with: EMAIL_REGEXP, message: 'Email invalid' },
            length: { minimum: 4, maximum: 254 }

  validates :phone, format: { with: PHONE_REGEXP, message: 'Phone invalid' }

  private

  def destroy_action
    puts 'Client success deleted'
  end

  def success
    puts 'Client was succes save'
  end

  def client_saved_to_db
    puts 'Client was success saved to database'
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :client
  belongs_to :picture
end

app/models/normalized_name.rb
# frozen_string_literal: true

class NormalizedName
  def self.before_save(product)
    return if product.name == product.name.capitalize

    product.name = product.name.capitalize
  end
end

app/models/picture.rb
# frozen_string_literal: true

class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_many :comments

  validates :name, length:
            { minimum: 3, maximum: 254,
              message: 'Input please correct name' }

  after_create_commit :client_saved_to_db
  before_save :normalized_name

  private

  def normalized_name
    if name == name.capitalize
      name
    else
      name.capitalize
    end
    # name == name.capitalize! ? name = name.capitalize! : false
  end

  def client_saved_to_db
    puts 'Client was success saved to database'
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy

  after_save_commit :success
  after_create :success
  after_update_commit :update_product_name, if: :update_product?
  after_destroy_commit :destroy_action

  # after_find { |product| puts "You have found an object!" }
  # after_initialize { |product| puts "You have initialized an object!" }

  validates :name, :description,
            length: { minimum: 3, maximum: 254,
                      message: 'Input please correct name' }
  before_save NormalizedName # class for inspect

  private

  def update_product?
    name.match?(/\A[A-z][a-zA-Z]+/)
  end

  def success
    puts 'Product was succes save'
  end

  def destroy_action
    puts 'Your product success deleted'
  end

  def update_product_name
    puts 'Your product was success updated'
  end
end

app/controllers/admin/comments_controller.rb
# frozen_string_literal: true

module Admin
  class CommentsController < ApplicationController
    def destroy
      @comment = Comment.find(params[:id])
      if comment.destroy
        flash[:success] = 'Success'
        redirect_to comment_path
      else
        flash[:error] = 'Error'
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:text)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)

    if @client.save
      flash[:success] = 'Success'
      redirect_to clients_path
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      flash[:success] = 'Success'
      redirect_to clients_path
    else
      flash[:error] = 'Error'
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id])

    if @client.destroy
      flash[:success] = 'Success'
      redirect_to clients_path
    else
      flash[:error] = 'Error'
    end
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :email, :phone)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      flash[:success] = 'Success'
      redirect_to comment_path
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true

class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.create(picture_params)

    if @picture.save
      flash[:success] = 'Success'
      redirect_to picture_path
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if picture.destroy
      flahs[:success] = 'Success'
      redirect_to picture_path
    else
      flahs[:error] = 'Error'
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:name)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    binding.pry

    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      flash[:success] = 'Success'
      redirect_to products_path
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      flash[:success] = 'Success'
      redirect_to products_path
    else
      flash[:error] = 'Error'
      render :edit
    end
  end

  def destroy!
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = 'Success'
      redirect_to products_path
    else
      flash[:error] = 'Error'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

module CommentHelper
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true

module PicturesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/clients/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= link_to 'Back', clients_path, class: 'btn btn-primary' %></td>
      <%= form_for @client do |f| %>
        <div class="field">
          <%= f.label :first_name %><br/>
          <%= f.text_field :first_name, required: true, class: "form-control" %>
        </div>
         <div class="field">
          <%= f.label :last_name %><br/>
          <%= f.text_field :last_name, required: true, class: "form-control" %>
        </div>
         <div class="field">
          <%= f.label :phone %><br/>
          <%= f.text_field :phone, required: true, class: "form-control" %>
        </div>
         <div class="field">
          <%= f.label :email %><br/>
          <%= f.text_field :email, required: true, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit 'Save', class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/clients/edit.html.erb
<%= render 'form' %>

app/views/clients/index.html.erb
<h1> Clients </h1>

<p><%= link_to "New client", new_client_path(@client)%></p>

<% @clients.each do |client|%>
  <p> <%= link_to "Client #{client.id}", client_path(client) %></p>
<%end%>

<p> <%= @clients.count %> Number of clients</p>

app/views/clients/new.html.erb
<%= render 'form' %>

app/views/clients/show.html.erb
<h1>Hello <%= @client.first_name%></h1>

<p><%= Time.now%></p>

<p><%= @client.first_name%></p>
<p><%= @client.last_name%></p>
<p><%= @client.email%></p>
<p><%= @client.phone%></p>

<p>client_id <b><%= @client.id %></></p>

<p><%= link_to "All clients", "/clients" %></p>

app/views/comments/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= link_to 'Back', comments_path, class: 'btn btn-primary' %></td>
      <%= form_for @comment do |f| %>
        <div class="field">
          <%= f.label :text %><br/>
          <%= f.text_field :text, required: true, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit 'Save', class:"btn btn-primary" %>
        </div>
      <% end %>

    </div>
    <div class="col"></div>
  </div>
</div>

app/views/comments/index.html.erb
<h1> Comments </h1>

<p><%= link_to "New comments", new_comment_path(@comment)%></p>

<% @comments.each do |comment|%>
  <p> <%= link_to "Comment #{comment.id}", comment_path(comment) %></p>
<%end%>

<p> <%= @comments.count %> Number of comments</p>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<h1> Comments</h1>

<p> <%= @comment.text %></p>

<p>comment_id <b><%= @comment.id %></b></p>

<p><%= link_to "All comments", "/comments" %></p>

app/views/home/index.html.erb
<div class="table table-hover container">
  <div class="col-md-12">
      <img class="mb-4" src= #'https://i.pinimg.com/originals/ab/b0/0d/abb00d63eac4b40cde91b99b480eb0f8.jpg' alt="" width="1300" height="700">
  <div/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polymorphic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %> 
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="container">
  <div class="row", "table table-hover">
    <div class="col-md">
      <%= link_to 'Back', pictures_path, class: 'btn btn-primary' %></td>
      <%= form_for @picture do |f| %>
        <div class="field">
          <%= f.label :nmae %><br/>
          <%= f.text_field :name, required: true, class: "form-control" %>
        </div>
        <div class="actions">
          <%= f.submit 'Save', class:"btn btn-primary" %>
        </div>
      <% end %>
    <div/>
    <div class="col"></div>
  <div/>
<div/>

app/views/pictures/index.html.erb
<h1>Pictures all</h1>

<p><%= link_to "New pictures", new_picture_path(@picture)%></p>

<% @pictures.each do |picture| %>
  <%= link_to "Picture #{picture.id}", picture_path(picture) %>
<%end%>

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1> Pictures</h1>

<p> <%= @picture.name %></p>

<p>picture_id <b><%= @picture.id %></b></p>

<p><%= link_to "All pictures", "/pictures" %></p>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <%= link_to 'Back', products_path, class: 'btn btn-primary' %></td>
      <%= form_for @product do |f| %>
        <div class="field">
          <%= f.label :nmae.name %><br/>
          <%= f.text_field :name, required: true, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :description %><br/>
          <%= f.text_area :description, required: true, class: "form-control" %>
        </div>
      
        <div class="actions">
          <%= f.submit 'Save', class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<h1> Products </h1>

<p><%= link_to "New product", new_product_path(@product)%></p>

<% @products.each do |product| %>
  <%= link_to "#{product.id} Product #{product.name}", product_path(product.id)%>
<%end%>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<h1> Product</h1>

<p> <%= @product.name %></p>
<p> <%= @product.description %></p>

<p>product_id <b><%= @product.id %></b></p>

<td><%= link_to 'Edit', edit_product_path(@product) %></td>
<td><%= link_to 'Destroy', product_path(@product), data: {method: :delete, confirm: 'Are you sure' }%></td>


<p><%= link_to "All products", "/products" %></p>

app/views/shared/_header.html.erb
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom,"navbar navbar-light" style="background-color: #e3f2fd;"">
    <a href="<%= root_path %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="root_path"></use></svg>
      <div>
       <div class='col-12 btn btn-primary'>Polymorphic</div>
      </div>
    </a>
    <div class='col-2 d-flex text-primary'>
      <%= Time.now.strftime("%d.%m.%Y %H:%M") %>
    </div>
    

    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= link_to 'Pictures', pictures_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Products', products_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Clients', clients_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Comment', comments_path, class: "nav-link" %>
      </li>
    </ul>
  </header>
</div>